#!/usr/bin/env python3
"""Create a PS2 boot ISO from a staged package, without Android HostFS."""
import argparse
import hashlib
from io import BytesIO
import os
from pathlib import Path
import struct
import tempfile
import time
from unittest.mock import patch

MARKER = ".cdogs-ps2-package"
SYSTEM_CNF = b"BOOT2 = cdrom0:\\CDOGS.ELF;1\r\nVER = 1.00\r\nVMODE = NTSC\r\n"


def iso_library():
    try:
        import pycdlib
    except ImportError as e:
        raise RuntimeError("ISO creation requires: python3 -m pip install -r "
                           "platform/ps2/requirements-iso.txt") from e
    return pycdlib


def package_entries(package):
    if not (package / MARKER).is_file():
        raise ValueError("Input must be a package generated by stage.py")
    elf = package / "cdogs-sdl.elf"
    with elf.open("rb") as f:
        header = f.read(52)
    if len(header) != 52 or header[:6] != b"\x7fELF\x01\x01" or \
            struct.unpack_from("<H", header, 18)[0] != 8 or \
            struct.unpack_from("<I", header, 36)[0] & 0x00FF0000 != 0x00920000:
        raise ValueError("Package ELF is not a little-endian PS2 R5900 executable")
    for required in ("data/guns.json", "graphics/font.png"):
        if not (package / required).is_file() or not (package / required).stat().st_size:
            raise ValueError(f"Missing runtime asset: {required}")
    entries, siblings = [], {}
    for path in sorted(package.rglob("*")):
        relative = path.relative_to(package)
        if relative.as_posix() == MARKER:
            continue
        if path.is_symlink() or not (path.is_file() or path.is_dir()):
            raise ValueError(f"Unsupported package entry: {relative}")
        if not relative.as_posix().isascii() or any(len(p) > 64 for p in relative.parts):
            # SDK CDFS discards the high byte of each Joliet character.
            raise ValueError(f"Filename outside PS2 CDFS/Joliet limits: {relative}")
        if len("cdfs:/" + relative.as_posix()) >= 512 or len(relative.parts) > 8:
            raise ValueError(f"Path outside PS2 CDFS/ISO9660 limits: {relative}")
        names = siblings.setdefault(relative.parent, set())
        if relative.name.lower() in names:
            raise ValueError(f"Case-insensitive filename collision: {relative}")
        names.add(relative.name.lower())
        if relative.name.upper() in {"SYSTEM.CNF", "CDOGS.ELF"} and relative.parent == Path("."):
            raise ValueError(f"Reserved disc boot filename: {relative}")
        entries.append((path, relative))
    for parent, names in siblings.items():
        # Game-local CDFS has 512 slots; non-root listings include '..'.
        # Root also gets SYSTEM.CNF (CDOGS.ELF already appears in entries).
        if len(names) + 1 >= 512:
            raise ValueError(f"Directory exceeds game CDFS entry limit: {parent}")
    for _, relative in entries:
        # The pinned SDK's splitPath still terminates its directory at byte 255.
        if len("/" + relative.parent.as_posix()) >= 255:
            raise ValueError(f"Parent path exceeds SDK CDFS limit: {relative}")
    return entries


class HashSink:
    def __init__(self):
        self.digest = hashlib.sha256()

    def write(self, data):
        self.digest.update(data)
        return len(data)


def hash_file(path):
    with path.open("rb") as f:
        return hashlib.file_digest(f, "sha256").hexdigest()


def verify_image(image, package, entries=None):
    """Read both boot records and every Joliet file back; compare content hashes."""
    pycdlib = iso_library()
    entries = entries if entries is not None else package_entries(package)
    # Pinned CDFS scans only sectors 16..19 and chooses the last type 1/2
    # descriptor. Assert it will select Joliet, not truncated primary names.
    selected = None
    with image.open("rb") as f:
        for sector in range(16, 20):
            f.seek(sector * 2048)
            block = f.read(2048)
            if block[1:6] != b"CD001":
                break
            if block[0] in (1, 2):
                selected = block
    if selected is None or selected[0] != 2 or selected[88:91] != b"%/E":
        raise ValueError("SDK CDFS cannot select the Joliet descriptor")
    iso = pycdlib.PyCdlib()
    opened = False
    try:
        iso.open(str(image))
        opened = True
        boot = BytesIO()
        iso.get_file_from_iso_fp(boot, iso_path="/SYSTEM.CNF;1")
        if boot.getvalue() != SYSTEM_CNF:
            raise ValueError("Incorrect PS2 boot record")
        elf_hash = HashSink()
        iso.get_file_from_iso_fp(elf_hash, iso_path="/CDOGS.ELF;1")
        if elf_hash.digest.hexdigest() != hash_file(package / "cdogs-sdl.elf"):
            raise ValueError("Disc boot ELF does not match the package")
        count = 0
        for path, relative in entries:
            name = "/CDOGS.ELF" if relative.as_posix() == "cdogs-sdl.elf" else "/" + relative.as_posix()
            record = iso.get_record(joliet_path=name)
            if path.is_dir():
                if not record.is_dir():
                    raise ValueError(f"Disc directory missing: {relative}")
            else:
                sink = HashSink()
                iso.get_file_from_iso_fp(sink, joliet_path=name)
                if sink.digest.hexdigest() != hash_file(path):
                    raise ValueError(f"Disc asset hash mismatch: {relative}")
                count += 1
        print(f"Verified PS2 boot records and {count} complete files in {image.name}")
    finally:
        if opened:
            iso.close()


def build_iso(package, output):
    package, output = package.resolve(), output.resolve()
    if output.is_relative_to(package):
        raise ValueError("ISO must be outside the staged package")
    entries = package_entries(package)
    pycdlib = iso_library()
    epoch = int(os.environ.get("SOURCE_DATE_EPOCH", "1609459200"))
    if not 315532800 <= epoch <= 4354819199:
        raise ValueError("SOURCE_DATE_EPOCH must be within 1980..2107")
    output.parent.mkdir(parents=True, exist_ok=True)
    # Normalize ISO timestamps only. No source asset or package is changed.
    timezone = os.environ.get("TZ")
    os.environ["TZ"] = "UTC"
    if hasattr(time, "tzset"):
        time.tzset()
    iso = pycdlib.PyCdlib()
    initialized = False
    temporary = None
    try:
        with patch("pycdlib.pycdlib.time.time", return_value=epoch):
            iso.new(interchange_level=3, joliet=3, vol_ident="CDOGS_SDL_PS2",
                    sys_ident="PLAYSTATION", app_ident_str="C-DOGS SDL PS2")
            initialized = True
            iso.add_fp(BytesIO(SYSTEM_CNF), len(SYSTEM_CNF),
                       iso_path="/SYSTEM.CNF;1", joliet_path="/SYSTEM.CNF")
            for path, relative in entries:
                if relative.as_posix() == "cdogs-sdl.elf":
                    iso.add_file(str(path), iso_path="/CDOGS.ELF;1", joliet_path="/CDOGS.ELF")
                    continue
                # Only the two boot files need primary ISO9660 records.
                # Joliet-only asset records avoid the primary 8.3/case/depth
                # limits without relying on ISO9660-1999 or Rock Ridge.
                joliet = "/" + relative.as_posix()
                if path.is_dir():
                    iso.add_directory(joliet_path=joliet)
                else:
                    iso.add_file(str(path), joliet_path=joliet)
            with tempfile.NamedTemporaryFile(dir=output.parent, prefix=".cdogs-disc-", suffix=".iso", delete=False) as f:
                temporary = Path(f.name)
            iso.write(str(temporary))
        verify_image(temporary, package, entries)
        temporary.replace(output)
        temporary = None
        print(f"ISO: {output} ({output.stat().st_size / 1048576:.1f} MiB)")
    finally:
        if initialized:
            iso.close()
        if temporary is not None:
            temporary.unlink(missing_ok=True)
        if timezone is None:
            os.environ.pop("TZ", None)
        else:
            os.environ["TZ"] = timezone
        if hasattr(time, "tzset"):
            time.tzset()


def main():
    root = Path(__file__).resolve().parents[2]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--package", type=Path, default=root / "out/package")
    parser.add_argument("--output", type=Path, default=root / "out/cdogs-sdl-ps2-silent.iso")
    args = parser.parse_args()
    build_iso(args.package, args.output)


if __name__ == "__main__":
    main()
