#!/usr/bin/env python3
"""Stage ELF + runtime assets, optionally converting audio to PS2 PCM on the PC."""
import argparse
import hashlib
import json
from pathlib import Path
import shutil
import subprocess
import wave
import zipfile

ROOT = Path(__file__).resolve().parents[2]
ASSETS = ("data", "graphics", "missions", "dogfights", "music", "sounds")
AUDIO = {".wav", ".ogg", ".mp3", ".it", ".mod", ".s3m", ".xm"}
SOURCE = {".blend", ".xcf", ".psd", ".aseprite", ".kra"}
MARKER = ".cdogs-ps2-package"


def decode(source, dest):
    # Force the WAV muxer even for .pcm sidecars. Keep the upstream filenames
    # for enumeration; the console loader resolves them to their PCM sidecars.
    subprocess.run(["ffmpeg", "-hide_banner", "-loglevel", "error", "-nostdin", "-y",
                    "-i", str(source), "-vn", "-map_metadata", "-1", "-ac", "2",
                    "-ar", "48000", "-c:a", "pcm_s16le", "-f", "wav", str(dest)], check=True)
    with wave.open(str(dest), "rb") as pcm:
        if (pcm.getnchannels(), pcm.getsampwidth(), pcm.getframerate()) != (2, 2, 48000):
            raise RuntimeError(f"Invalid PCM conversion: {source}")


def stage(source, elf, output, audio=False, rfa_root=None):
    source, elf, output = source.resolve(), elf.resolve(), output.resolve()
    # Never clear a checkout, an ancestor, the ELF's folder or arbitrary user data.
    if source.is_relative_to(output) or elf.is_relative_to(output):
        raise ValueError("Package output would overwrite input")
    if any(output.is_relative_to(source / name) for name in ASSETS):
        raise ValueError("Package output cannot be inside source assets")
    if elf.read_bytes()[:4] != b"\x7fELF":
        raise ValueError("Input is not a valid ELF")
    if output.exists():
        if not (output / MARKER).is_file() and any(output.iterdir()):
            raise ValueError(f"Nonempty output is not a generated package: {output}")
        shutil.rmtree(output)
    if audio and not shutil.which("ffmpeg"):
        raise RuntimeError("Audio staging requires ffmpeg on the PC")
    output.mkdir(parents=True)
    (output / MARKER).write_text("Generated by platform/ps2/stage.py\n")
    shutil.copy2(elf, output / "cdogs-sdl.elf")
    count, pcm_bytes = 0, 0
    for name in ASSETS:
        directory = source / name
        if not directory.is_dir():
            raise ValueError(f"Missing asset directory: {directory}")
        for path in sorted(directory.rglob("*")):
            relative = path.relative_to(source)
            dest = output / relative
            if path.is_dir():
                dest.mkdir(parents=True, exist_ok=True)
            elif path.is_file() and path.suffix.lower() not in SOURCE:
                dest.parent.mkdir(parents=True, exist_ok=True)
                if path.suffix.lower() in AUDIO:
                    if not audio:
                        continue
                    pcm = dest if path.suffix.lower() == ".wav" else Path(str(dest) + ".pcm")
                    decode(path, pcm)
                    if pcm != dest:
                        dest.touch()
                    count += 1
                    pcm_bytes += pcm.stat().st_size
                else:
                    shutil.copy2(path, dest)
    (output / "config").mkdir()
    # Retain both code licensing and all asset attribution documentation.
    for name in ("COPYING", "AUTHORS", "README.md"):
        if (source / name).is_file():
            shutil.copy2(source / name, output / name)
    shutil.copytree(source / "doc", output / "doc", dirs_exist_ok=True)
    shutil.copy2(source / "platform/ps2/README.md", output / "README-PS2.md")
    sdk_license = source / "platform/ps2/LICENSE-PS2SDK.txt"
    if sdk_license.is_file():
        shutil.copy2(sdk_license, output / "PS2SDK-LICENSE.txt")
    if audio:
        if not rfa_root or not (rfa_root / "LICENSE").is_file():
            raise ValueError("--audio requires --rfa-root (RFAuds2 license must accompany the binary)")
        shutil.copy2(rfa_root / "LICENSE", output / "RFAuds2-LICENSE.txt")
    hashes = {str(p.relative_to(output)): hashlib.sha256(p.read_bytes()).hexdigest()
              for p in sorted(output.rglob("*")) if p.is_file()}
    manifest = {"audio": "RFAUDS2 PCM" if audio else "OFF", "decoded_files": count,
                "pcm_bytes": pcm_bytes, "dependencies": json.loads((source / "platform/ps2/deps.lock.json").read_text()),
                "sha256": hashes}
    (output / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    print(f"Staged {output}; converted {count} audio files ({pcm_bytes / 1048576:.1f} MiB)")


def archive(output, dest):
    if dest.resolve().is_relative_to(output.resolve()):
        raise ValueError("ZIP must be outside the staged directory")
    dest.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(dest, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=6) as bundle:
        for path in sorted(output.rglob("*")):
            relative = str(Path("cdogs-sdl") / path.relative_to(output))
            info = zipfile.ZipInfo(relative + ("/" if path.is_dir() else ""), (1980, 1, 1, 0, 0, 0))
            info.external_attr = (0o40755 if path.is_dir() else 0o100644) << 16
            info.compress_type = zipfile.ZIP_DEFLATED
            bundle.writestr(info, b"" if path.is_dir() else path.read_bytes())
    print(f"ZIP: {dest} ({dest.stat().st_size / 1048576:.1f} MiB)")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--elf", type=Path, default=ROOT / "out/ps2/cdogs-sdl.elf")
    parser.add_argument("--output", type=Path, default=ROOT / "out/package")
    parser.add_argument("--audio", action="store_true")
    parser.add_argument("--rfa-root", type=Path)
    parser.add_argument("--zip", type=Path)
    parser.add_argument("--iso", type=Path, help="Bootable disc image (install requirements-iso.txt first)")
    args = parser.parse_args()
    stage(ROOT, args.elf, args.output, args.audio, args.rfa_root)
    if args.zip:
        archive(args.output, args.zip)
    if args.iso:
        from disc import build_iso
        build_iso(args.output, args.iso)


if __name__ == "__main__":
    main()
